user.login=test1233314143
user.password=testuser
url.base=https://pizzeria.skillbox.cc
url.accountPage=${url.base}/my-account/
url.editAccountPage=${url.base}/my-account/edit-account/
url.menuPage=${url.base}/product-category/menu/
url.pizzaPage=${url.base}/product-category/menu/pizza/
url.checkoutPage=${url.base}/checkout/
url.basketPage=${url.base}/cart/
url.promoPage=${url.base}/promo/
url.bonusPage=${url.base}/bonus/
url.deliveryPage=${url.base}/delivery/
