name: Run Tests and Generate Allure Report

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Install Chrome 139
        run: |
          sudo apt-get update
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install ./google-chrome-stable_current_amd64.deb

      - name: Remove preinstalled ChromeDriver
        run: sudo rm -f /usr/bin/chromedriver

      - name: Install matching ChromeDriver
        run: |
          set -e
          CHROME_VER=$(google-chrome --version | sed -E 's/.* ([0-9]+)\..*/\1/')
          DRIVER_VER=$(wget -qO- "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VER}")
          wget -N "https://chromedriver.storage.googleapis.com/${DRIVER_VER}/chromedriver_linux64.zip"
          unzip -o chromedriver_linux64.zip -d chromedriver_temp
          sudo mv chromedriver_temp/chromedriver /usr/local/bin/chromedriver
          sudo chmod +x /usr/local/bin/chromedriver
          chromedriver --version

      - name: Run tests
        run: mvn clean test

      - name: "Debug: Check Allure Results"
        run: ls -la target/allure-results

      - name: Upload Allure Results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: target/allure-results

      - name: Install Allure CLI
        run: |
          sudo apt-add-repository ppa:qameta/allure -y
          sudo apt-get update
          sudo apt-get install allure -y

      - name: Generate Allure Report (CLI)
        run: |
          allure generate target/allure-results --clean -o target/allure-report

      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: target/allure-report
